### ISSUE TITLE
Crashing issue with SimplySkills

### ISSUE THREAD

**Issue by HaXrDEV** [someaddons/armordamagescaling#3]
When this mod is installed it causes a crash when a player has the CyclonicCleaveEffect from SimplySkills applied. (Gained by casting the Ascendency ability CyclonicCleave)

Removing this mod makes the issue go away.

![crashlog](https://github.com/user-attachments/files/16574267/message.8.txt)

**Comment by HaXrDEV** [comment]
armordamagescale-fabric-1.20.1-3.0
simplyskills 1.5.0+1.20.1
cloth-config 11.1.118
player-animator 1.0.2-rc1+1.20
puffish_attributes 0.5.0
puffish_skills 0.12.2
spell_engine 0.15.8+1.20.1
spell_power 0.11.1+1.20.1
trinkets 3.7.2

**Comment by someaddons** [comment]
couldnt reproduce it, but added more safety checks to 3.1

**Comment by HaXrDEV** [comment]
I can't seem to reproduce it either in a minimal environment and all mods updated. Crossing my fingers that updating the mods in my modpack will do the trick. Thanks for your time.
