### ISSUE TITLE
Problem with Red Alert enchant of Spellbound mod

### ISSUE THREAD

**Issue by slammaja** [someaddons/armordamagescaling#5]
Hi, 
I encountered a problem with Spellbound enchantments mod (https://www.curseforge.com/minecraft/mc-mods/spellbound-enchantments) with your mod installed. There is Red Alert enchant which generates barrier that prevents next source of damage, But this doesn't work against damage caused by mobs when Armor & damage scaling is present, against other sources of damage it works as it should.

MC 1.20.1, Fabric - 0.16.5
A & D scaling - 3.1
Spellbound - 1.17.0

**Comment by someaddons** [comment]
ye the enchantments mod is mixin into a bad place, should modify damage at the top of the hurt function like everyone else does, report to the enchantment mod
